<a href="https://colab.research.google.com/github/mangeshtate/Python-Collab-Notebook/blob/main/Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
renewable_series=("Solar","Wind","Hydropower","Biomass Energy","Geothermal Energy","Hydrogen","Tidal Energy")
renewable_sources=pd.Series(renewable_series)

print("Renewable Energy Sources:")
print(renewable_sources)


Renewable Energy Sources:
0                Solar
1                 Wind
2           Hydropower
3       Biomass Energy
4    Geothermal Energy
5             Hydrogen
6         Tidal Energy
dtype: object


In [ ]:
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}
projects_df = pd.DataFrame(data)
print("\nGreen Technology Projects DataFrame:")
projects_df.head()
projects_df.tail(3)


Green Technology Projects DataFrame:


Project  Technology  Capacity (MW)  Cost (Million $)  \
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [ ]:
high_capacity_projects = projects_df[projects_df["Capacity (MW)"] > 100]

print("\nProjects with Capacity Above 100 MW:")
high_capacity_projects


Projects with Capacity Above 100 MW:


Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [ ]:
projects_df["Cost per MW"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]

print("\nDataFrame with Cost per MW Column:")
projects_df.head()


DataFrame with Cost per MW Column:


Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4       Idaho             2023     2.500000

In [ ]:
import pandas as pd

data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

projects_df = pd.DataFrame(data)

grouped_data = projects_df.groupby("Technology")["Capacity (MW)"].sum()

print("\nTotal Capacity by Technology:")
print(grouped_data)



Total Capacity by Technology:
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [ ]:
import numpy as np

# Data
projects = ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"]
technology = np.array(["Solar", "Wind", "Hydropower", "Solar", "Geothermal"])
capacity = np.array([150, 300, 200, 50, 100])  # MW

# Grouping by Technology
unique_tech, inverse_idx = np.unique(technology, return_inverse=True)
total_capacity = np.zeros(len(unique_tech), dtype=int)

for i, cap in enumerate(capacity):
    total_capacity[inverse_idx[i]] += cap

# Display results
print("\nTotal Capacity by Technology (NumPy):")
for tech, cap in zip(unique_tech, total_capacity):
    print(f"{tech}: {cap} MW")




Total Capacity by Technology (NumPy):
Geothermal: 100 MW
Hydropower: 200 MW
Solar: 200 MW
Wind: 300 MW


In [ ]:
A=np.ones(4)
A2=np.ones((2,2))
print(A)
print(A2)

#M=np.zeros(4)
#print(M)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [ ]:
M=np.zeros(4)
print(M)

[0. 0. 0. 0.]


In [ ]:
M = np.identity(4)
print(M)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np

energy_consumption = np.array([1200, 3000, 2500, 1000, 2500, 3050])
print("Original 1D Array:\n", energy_consumption)


Original 1D Array:
 [1200 3000 2500 1000 2500 3050]


In [ ]:
import numpy as np

energy_consumption = np.array([1200, 3000, 2500, 1000, 2500, 3050])
print("Original Array:\n", energy_consumption)

# Reshape to 2 rows and 3 columns
reshaped_2x3 = energy_consumption.reshape(2, 3)
print("\nReshaped to 2x3:\n", reshaped_2x3)

# Reshape to 3 rows and 2 columns
reshaped_3x2 = energy_consumption.reshape(3, 2)
print("\nReshaped to 3x2:\n", reshaped_3x2)

# Reshape to column vector (6x1)
reshaped_6x1 = energy_consumption.reshape(6, 1)
print("\nReshaped to 6x1 (column vector):\n", reshaped_6x1)


Original Array:
 [1200 3000 2500 1000 2500 3050]

Reshaped to 2x3:
 [[1200 3000 2500]
 [1000 2500 3050]]

Reshaped to 3x2:
 [[1200 3000]
 [2500 1000]
 [2500 3050]]

Reshaped to 6x1 (column vector):
 [[1200]
 [3000]
 [2500]
 [1000]
 [2500]
 [3050]]


In [ ]:
import numpy as np

energy_consumption = np.array([1200, 3000, 2500, 1000, 2500, 3050])

# Reshape to 2x3
reshaped = energy_consumption.reshape(2, 3)
print("Reshaped (2x3):\n", reshaped)

# Transpose
transposed = reshaped.T
print("\nTransposed (3x2):\n", transposed)


Reshaped (2x3):
 [[1200 3000 2500]
 [1000 2500 3050]]

Transposed (3x2):
 [[1200 1000]
 [3000 2500]
 [2500 3050]]


In [ ]:
resize_arr = np.resize(reshaped,(3,3))
print(resize_arr)

[[1200 3000 2500]
 [1000 2500 3050]
 [1200 3000 2500]]


In [ ]:
import numpy as np

energy_consumption = np.array([1200, 3000, 2500, 1000, 2500, 3050])
print("Original Array:\n", energy_consumption)

# Resize to 2x4 → 8 elements (will repeat values)
resized_2x4 = np.resize(energy_consumption, (2, 4))
print("\nResized to 2x4:\n", resized_2x4)

# Resize to 3x3 → 9 elements (repeats)
resized_3x3 = np.resize(energy_consumption, (3, 3))
print("\nResized to 3x3:\n", resized_3x3)

# Resize to 6x1 (like reshape but with resize)
resized_6x1 = np.resize(energy_consumption, (6, 1))
print("\nResized to 6x1:\n", resized_6x1)


Original Array:
 [1200 3000 2500 1000 2500 3050]

Resized to 2x4:
 [[1200 3000 2500 1000]
 [2500 3050 1200 3000]]

Resized to 3x3:
 [[1200 3000 2500]
 [1000 2500 3050]
 [1200 3000 2500]]

Resized to 6x1:
 [[1200]
 [3000]
 [2500]
 [1000]
 [2500]
 [3050]]


In [ ]:
import pandas as pd
import numpy as np

data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

df = pd.DataFrame(data)

# Check for null values
print("\nCheck null values (True means NaN present):")
print(df.isnull())

# Count total null values per column
print("\nCount of null values per column:")
print(df.isnull().sum())

# Check if any null value exists in whole DataFrame
print("\nAny null values in DataFrame?")
print(df.isnull().values.any())



Check null values (True means NaN present):
   Energy Source  Energy Consumption (MWh)  Cost (Million $)
0          False                     False             False
1          False                      True             False
2          False                     False              True
3          False                      True             False
4          False                     False             False
5          False                     False              True

Count of null values per column:
Energy Source               0
Energy Consumption (MWh)    2
Cost (Million $)            2
dtype: int64

Any null values in DataFrame?
True


In [ ]:
import pandas as pd
import numpy as np

data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

df = pd.DataFrame(data)
print(df)

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN


In [ ]:
import pandas as pd
import numpy as np

# Original dataset
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

energy_df = pd.DataFrame(data)

# Drop rows with NaN values
cleaned_df = energy_df.dropna(axis=0)

# Display first rows of cleaned DataFrame
print("\nCleaned DataFrame:")
print(cleaned_df.head())

ec_n=energy_df["Energy Consumption (MWh)"].mean()
c_n=energy_df["Cost (Million $)"].mean()
print(ec_n)
print(c_n)


Cleaned DataFrame:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0
2450.0
250.0


In [ ]:
import pandas as pd
import numpy as np

# Your dataset
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df, "\n")

# Forward fill (modern way)
df_ffill = df.ffill()
print("After Forward Fill:\n", df_ffill, "\n")

# Backward fill (modern way)
df_bfill = df.bfill()
print("After Backward Fill:\n", df_bfill)


Original DataFrame:
   Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN 

After Forward Fill:
   Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    1200.0             400.0
2    Hydropower                    2900.0             400.0
3    Geothermal                    2900.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0 

After Backward Fill:
   Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                 

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Your dataset
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
from sklearn.impute import SimpleImputer
scaler=MinMaxScaler()

energy_df= pd.DataFrame(data)

energy_df[["Energy Consumption (MWh)","Cost (Million $)"]]=scaler.fit_transform(energy_df[["Energy Consumption (MWh)","Cost (Million $)"]])
#
print("Original DataFrame:\n", df, "\n")
print("Data After Normalization")
print(energy_df)

Original DataFrame:
   Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN 

Data After Normalization
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                      0.00               0.2
1          Wind                       NaN               1.0
2    Hydropower                      0.85               NaN
3    Geothermal                       NaN               0.0
4       Biomass                      0.65               0.4
5       Nuclear                      1.00               NaN


In [ ]:
#Standardization
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Your dataset
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
from sklearn.impute import SimpleImputer
scaler=StandardScaler()
energy_df = pd.DataFrame(data) # Re-create the dataframe to work with original values before imputation and scaling
imputer = SimpleImputer(strategy='mean') # Define the imputer
energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]] = imputer.fit_transform(
    energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]]
)

energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]] = scaler.fit_transform(
    energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]]
)
print("Data After Standardization")
print(energy_df)

Data After Standardization
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                 -2.005893         -0.654654
1          Wind                  0.000000          1.963961
2    Hydropower                  0.722121          0.000000
3    Geothermal                  0.000000         -1.309307
4       Biomass                  0.080236          0.000000
5       Nuclear                  1.203536          0.000000


In [ ]:
import pandas as pd
import numpy as np

data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

energy_encoded_df=pd.get_dummies(energy_df,columns=["Energy Source"])
print("Data After One hot encoding")
print(energy_encoded_df)



Data After One hot encoding
   Energy Consumption (MWh)  Cost (Million $)  Energy Source_Biomass  \
0                 -2.005893         -0.654654                  False   
1                  0.000000          1.963961                  False   
2                  0.722121          0.000000                  False   
3                  0.000000         -1.309307                  False   
4                  0.080236          0.000000                   True   
5                  1.203536          0.000000                  False   

   Energy Source_Geothermal  Energy Source_Hydropower  Energy Source_Nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False              

In [ ]:
pd.read_csv("nba.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'nba.csv'